### ISSUE TITLE
Version conflict for script vr_companion.py

### ISSUE THREAD

**Issue by rabbivr** [Ofisare/VRCompanion#2]
I found that in my computer, when I used  FreePieOpenVR 1.2, only the script "vr_companion_v1.0.py" in the scripts folder in FreePieOpenVR 1.2.zip can run successfully. If I run other script named "vr_companion.py" (such as the one in  VRCompanion-Release_1.2.3.zip), some errors such as "'NoneType" object has no attribute 'trackMeleeRight'" will appear.

**Comment by rabbivr** [comment]
I found that as long as I replace all the code involving the use of variable "item" with the old version, the new version of vr_companion.py can run properly.
![1](https://github.com/Ofisare/VRCompanion/assets/172621025/d31768e0-86f6-4ac7-8033-6e15f2dd701f)

But I'm not sure if there might be any potential issues after making this change in the code.

**Comment by Ofisare** [comment]
Version 1.2.3 actually fixes this issue, an accidental partial update lead to the problem not resolving itself.
Thx for reaching out.
