### ISSUE TITLE
Local variable 'skipUpdate' referenced before assignment

### ISSUE THREAD

**Issue by drowhunter** [Ofisare/VRCompanion#5]
This error occurs when running vr_companion.py on line 205

![image](https://github.com/Ofisare/VRCompanion/assets/2817488/61cb9574-81e0-49bb-ac1a-53b7846cbca5)

**Comment by Ofisare** [comment]
Python for the win ..., suddently it seems to be a local variable only, as before it is initialized at the top of the script ~ line 44, but now that there is an assignment in the function as well ...

**Comment by Ofisare** [comment]
Fixed, thanks for the hint :-)
